#!/usr/bin/env bash
allowed_branches_regex=$(git show main:allowed_branches |
  tr '\n' '|' |
  sed 's/.$//')
this_branch=$(git rev-parse --abbrev-ref HEAD)
grep -Eq "$allowed_branches_regex" <<< "$this_branch" && exit 0
>&2 echo "ERROR: This branch is not on 'allowed_branches'; blocking push: $this_branch"
exit 1
