Vagrant.configure("2") do |config|
  config.vm.box = "faux-marcus"
  config.vm.network :forwarded_port, guest: 22, host: 65522
  config.vm.provider "qemu" do |vm|
    vm.arch = "arm64"
    vm.cpu = "host"
    vm.net_device = "virtio-net-pci"
    vm.extra_qemu_args = %w(-bios "/opt/homebrew/share/qemu/edk2-aarch64-code.fd")
  end
end

