storage:
    filesystems:
        - name: ENC[AES256_GCM,data:ZVDT,iv:oILbHdJPSYs/2d3kn9tg5fY6/wRbGqeRcLjQnKgd/Qk=,tag:sgIosGjzA/J9jQ7NRZfXYA==,type:str]
          mount:
            device: ENC[AES256_GCM,data:2K/bhGA8ctcqC36Dz6UefT3QqShOzQ==,iv:VTRUEBAFyRRZ8DeoKuVNrWAv3AgG1Grqkp6O8fsnJGQ=,tag:zP/rU/fVT1+olba4ZrluYA==,type:str]
            format: ENC[AES256_GCM,data:oiXuktI=,iv:I7YBQQIkTwCbPHpC66jhPkF0f9PeJA+NbhO69G0JSbc=,tag:3WNJKTQICxrKSglEBZlR7A==,type:str]
    directories:
        - path: ENC[AES256_GCM,data:McwCu2bJmWw3ULHgCQ==,iv:jMc5legXoDC+hm9F9YFEYAoC4iT/rcweHzAtSnk82F0=,tag:/rnAMDuYlI+Z20Fj88iGzQ==,type:str]
          mode: ENC[AES256_GCM,data:+hE6,iv:5AylihHAbruzOE9r8vcDwkmKgryc978rnn/9QwBqNSU=,tag:WE+Ml2/hwFQL4Km/HzaJWg==,type:int]
          user:
            name: ENC[AES256_GCM,data:GU0a04Y0,iv:37pS0FpRm8qoncVC1OSBaC8VbHCyBwZs5SvLDA3OGUk=,tag:PRJOvsmVfYr/g83wC3TmVg==,type:str]
    files:
        - filesystem: ENC[AES256_GCM,data:Q483,iv:Ov2MQ1Yn2W5cB87+mkV6c4B47U7rPeyAdmeWkEG5M+E=,tag:x4Qx+0Fly/QhABiWWtv7WA==,type:str]
          path: ENC[AES256_GCM,data:xOlIUOhAnk21,iv:kF5/qyv/Yxxc96zyTd3nyQGQgVtciK10OkvSCYb4XX4=,tag:HgGoNfcRsET/6uqnlknKFQ==,type:str]
          mode: ENC[AES256_GCM,data:/fXa,iv:7gJYJUEmoH2aNRcXpez5EMdFlRKl0F/RiMHmzXBnHuc=,tag:vwUcMEaNNanCrOYa5xubKw==,type:int]
          append: ENC[AES256_GCM,data:PQgK9w==,iv:76qmBluOglyImtFkrwsW3f6Umrdj5BxeRuDQhAlTxn8=,tag:pm1WC2PAibH3XgbEl0RYQg==,type:bool]
          contents:
            inline: ENC[AES256_GCM,data:/oLAjjlcJkdejbOsBn9yhS1DYkv9E7AE8mVtVi1ecq2FcKGV/CbEiz/X2vF58Fs8uos=,iv:/zPcVZ19hHvS16BgbNnOqXzmWsgyGR6YHfvynijXXCM=,tag:wcpTIW4MiXZDUUYQQG1u/A==,type:str]
        - path: ENC[AES256_GCM,data:g1aQP6Tnn7MNIVYxOZlehOTLFwXR420D,iv:WEg0BRA+UeHJxovgBEt4e7TEETuGBNOKP+lVeRqSVDY=,tag:4CPpSbkv04DP6SUiuOxiQw==,type:str]
          mode: ENC[AES256_GCM,data:/fXa,iv:7gJYJUEmoH2aNRcXpez5EMdFlRKl0F/RiMHmzXBnHuc=,tag:vwUcMEaNNanCrOYa5xubKw==,type:int]
          contents:
            inline: ENC[AES256_GCM,data:5rDg2GoDl1KStWaOZo3/IssAT8i/HnnKCUTE+QJtRxa4X6qBAWF7p16g+94=,iv:z+UDJpnRgdmUmO/8git+mjCe0ZfTvy/HE+PUCsroYak=,tag:Ep0+Jq9wstdjKp3ldH1/oA==,type:str]
        - path: ENC[AES256_GCM,data:DC1BC9ZFTZpiaEJO3vfGck9GGzvjeyMbfgbzLPQVjeOeNLM=,iv:etfeT5bFtB4LertFAGLqm2NZk/+K8viSdi6xAiXYLwE=,tag:sD5XNLIcf97hcd6cnyOiJQ==,type:str]
          mode: ENC[AES256_GCM,data:/fXa,iv:7gJYJUEmoH2aNRcXpez5EMdFlRKl0F/RiMHmzXBnHuc=,tag:vwUcMEaNNanCrOYa5xubKw==,type:int]
          contents:
            inline: ENC[AES256_GCM,data:J4riGNVzLiWkKIu73CeEIbXElg06ifaxvpf6ZHG7T7T7wtclJFO1ttJXHicebvDp2+jH6MJMnIlg2gMCUZGxIYadhMESqeB06PDMr0szSPcKyXAFGTGpZNVvgF9I/yf1GiF2BXxgfUYN+3J8zrQp5+9sB/xXZEpeYW+Ss+EP8UU0Md16uI/05QV9EVmMwm+Rs+x0GpsklXtQoyv4KuTtPpYTNrRHQlE//bS0t93mPkoJNIHjEYRpsZuGLA0MGCP0dmbxh+Bb2BleYIZBxsvFxLgI65jS17ee6SZdVGlzMbZ6xcnvOMP2UW4rQ2e+0NA=,iv:aQH/wRfLK043rnzevrEb9dbLr8bH9yr41atTQtkCW5g=,tag:hseXfYI4tCmboWm8/awRrg==,type:str]
        - path: ENC[AES256_GCM,data:xFmoAtLSu+ZIu+SrQ4js+UacgiRUrMTMHfWO1fHZzPomyUVA,iv:zHE+t3xowm1qP26aLLnPPOovzZ9ojZC/OLrziAqoDQk=,tag:niYRBkNM5JQECVLyufcrcQ==,type:str]
          mode: ENC[AES256_GCM,data:/fXa,iv:7gJYJUEmoH2aNRcXpez5EMdFlRKl0F/RiMHmzXBnHuc=,tag:vwUcMEaNNanCrOYa5xubKw==,type:int]
          contents:
            inline: ENC[AES256_GCM,data:u/thJcL8CwbqohgcX5NaybIZcote+cdv926WdbgUFqoMEzhAeSIODcoUN8RYiTaAqvzCWmy0erPe0dfYZ2RjJanY5tTID0HR2u8=,iv:UKwfF1l5/rAo7CtRpOLs6kwPIKItZtM/iiCSeXVylLQ=,tag:BcBAWgCSQxrzCIVQCU5Rcg==,type:str]
            #ENC[AES256_GCM,data:xSJDYP1igfYa5G6ChIk6ogPoC8eKucu79WB5Gqn6pOvtRtigL3zk74Lx4PuSbw==,iv:v1iMwG05GyqVy9IR7kVQquZqQUzZ7eIiL7XXJtc2/7I=,tag:GT3HrvtCXrWGD3z/cbdhhw==,type:comment]
            #ENC[AES256_GCM,data:RHQ7/OqVkozSqL14bfuHAFi6qYsJjJkXD27sfH/JZDzXT5/cNRLUrNfWF60g1hFcMje2qsshDfnXMwRgi6DarC+LrQ==,iv:rTdGrB0iWZqfzoli71G/sLd4ocVL4Xqs7jGReetsSvk=,tag:qtTLNQhfY+txWKLIZaM32g==,type:comment]
        - path: ENC[AES256_GCM,data:kHSSl/ZqlLTCocKyE1KMKu3LHS0qrSg=,iv:W92Nd3xcKUoau81EGOGFjUl2yavhv2ta7x3xXABc/rk=,tag:UPZBWXrtYsVadRNfTISQYA==,type:str]
          mode: ENC[AES256_GCM,data:JvKM,iv:q7j4/MzEtLUgfIhMOh7lYMHIBzRW53vafZxG51bdfQc=,tag:c8MwPrHz8IguIcGjuz2aCQ==,type:int]
          user:
            name: ENC[AES256_GCM,data:xmeWQuXU,iv:jvb53NH7Losg4xpddeYLUCIz2PATKwq0o+30gPktRFM=,tag:7ynrJs3Pr8gTWayMcZGPAw==,type:str]
          contents:
            inline: ENC[AES256_GCM,data:DAPr2VbNqVFAZ/G/JHDVpuiPjpoXIn7HYN2O41/d/BTuF/opkUiMTTKp6zUHz/yQjlaCvIweoN9myaYvCSpcXnZSzXNT2oCZ+//uCa5pmQBkaQBLKQJwCrOGm822oWR1hGRxjgomnItCjLycQexTLDzxOOyaTWCv2sBHhND5QuuKTRFHgJFz,iv:pa+7o9vxn6AkOoOlMppCTggcQi0uQUgx61Xd+OWSonQ=,tag:rt4fOmQu0jo2s5tnQznlPg==,type:str]
        - path: ENC[AES256_GCM,data:sGf+aAV0H2IHjJdtsrek4LfbJz1KhEo8b0llsnNkfG8w,iv:xN3vlihxly8DovwbP4g6deXhGZ9eIIdYDDoonnk3K4E=,tag:HJev76iZjMruKH8PQ9WMrA==,type:str]
          mode: ENC[AES256_GCM,data:/fXa,iv:7gJYJUEmoH2aNRcXpez5EMdFlRKl0F/RiMHmzXBnHuc=,tag:vwUcMEaNNanCrOYa5xubKw==,type:int]
          user:
            name: ENC[AES256_GCM,data:xmeWQuXU,iv:jvb53NH7Losg4xpddeYLUCIz2PATKwq0o+30gPktRFM=,tag:7ynrJs3Pr8gTWayMcZGPAw==,type:str]
          contents:
            remote:
                url: ENC[AES256_GCM,data:G6nR7XKyk/N20+MMj9FmdykLoBUqHcmmUkUeYhGOirQgSAIBQYB8wqWdYHV9/PfwFlSzFJpYF9boLxsMZ6aPDQ1o4ANt1CymX0Uv8P6MkcVa3gCnIZ69bM1ZBJ9VNff8BSK2cmsRkElHHr2mSTc=,iv:tJaSSUrFb2yUejlcKAsbr5r69yBQ+AKxl6YDwUxJN2U=,tag:mwdRH5rA0t6+Ef8diqqrWw==,type:str]
                verification:
                    hash:
                        function: ENC[AES256_GCM,data:K9TFrSX2,iv:8BqET6ZwpiQHIRnBltRrm+oD7D1NJU75JoTFYZ8rOW4=,tag:iIVXwuz53g/TbPWEMjYUzg==,type:str]
                        sum: ENC[AES256_GCM,data:KWCH6jUqFzvtkvUTsld8LYZM71hfdcGVC28GYcPJg2sPhK2oIcsBr8muLYTnRt+VOYXyYCeH0Q9+eTt0Ci7zmi2USkpv7GaJQP8EAlL0bWvleR+YkpscjgdRn5HhCcu8gRv4P2oH8gn0cgEjL0U3MFeaa5QRzav344tzw4vL6ec=,iv:f7YpFcmT6TRu24ClmegkUW4xGGfDANtfWK69pjmFG+o=,tag:FrZu02WIILShqmvSRVIjpg==,type:str]
passwd:
    groups:
        - name: ENC[AES256_GCM,data:m7pTuOG26xlwmsi/,iv:t+Lo2mYksKZmsrFal4QxJkPKnz5Nlo6Twpk9w/g4KPM=,tag:EtYjxl2AT8L/9FHcV5pzBg==,type:str]
          gid: ENC[AES256_GCM,data:YnX7Qw==,iv:XqxbFsj6gsXMDOedf+Pavt9FJnhhTApTFVGFzojmXWg=,tag:tNEHJFvnvEnJYozBK1UKKQ==,type:int]
    users:
        - name: ENC[AES256_GCM,data:7rkw88GQ,iv:BBGwIWcXYMtSW4BX0bEkmxkwPnxf2qtFm9nhGX7e0jk=,tag:WNGNbhOezKQbdLJmv0eyLA==,type:str]
          uid: ENC[AES256_GCM,data:S5nueQ==,iv:4D2YSD8Lg4yA+syQHMs/+a/YwqTmGXJomzWC1meD04A=,tag:oQ2eKNOJdWbunT3wjzxCEw==,type:int]
          groups:
            - ENC[AES256_GCM,data:ZcYKn0zurUWaF3V+,iv:ud8XkvBxsnvb+9RxKcVwcrgMihDZPqXtar1AGyLdDVw=,tag:SHtqEdgOaXivhz4SX/9+lQ==,type:str]
            - ENC[AES256_GCM,data:713e6A==,iv:2NizvRZzVs6L6SUK50uSBs5VlypV0J834TpNRc2HccA=,tag:4kXPtfVEubtH+RM8ZTJ2sg==,type:str]
            - ENC[AES256_GCM,data:IuCTHwue,iv:LWqi7gMUEqRI/gLPqCmVByJwNIF2tSSgFc9DGW6Dty4=,tag:iy5p9sr/3BFi5Zrj4NW34w==,type:str]
          ssh_authorized_keys:
            - ENC[AES256_GCM,data:ESAx9CRVbDWUJ5DjOTRnSXPDUROwUOtRcDP73Awu3h/zVltX7nuhG+wUlQaNfrgXRSSALb5F39Odq6m3FaOtFZ0RVTRfab/+w2Qkmd4oRx54FA3rn4/N769uTmZNU3yZ/qhDU9zL3WdVpKKPQMM8U880Bgphg7E+iB1rnPQCQUN25O+rc5fN1t5Glv0yChPsmAYwdFwSQlvuqoZJ+NML5RkaotV55bWk2LqLf3ZeUYsrRAB0jPL3C1HujaZCkkQdQw0h0KQilcJ+C0Q2w3zAbCTDZqtl6bMZV5Q+qMuWB7+GCqLMxHswXB8Vn+ukL08CRb71u9rs6ezp+JWaqZO76yuKgcNwqoU74srCU0ZGuBNzXv5IXhtgMdyFcOOJybzGQ0O7yMi2rprn+RRIm4r+xfgNOElTPsiNOtyWPtEDJWwDE3WdrHnJKBX73AVyOtwP5q27DWqjWhbjK6nGBVgAY9gTfqcOmQ5Stx8N8XT1Z8FIM2cM3cSkII66cmg+sjk9PZGoy9jK2L7zh5Hhs2HsL+myeq7MOc21FpPwG4fVMCzEJk8QD4V1gDLmkljvK4Mu3YL5UMvgI4ynb2SwVxRtjTCF0xXTMwHEY/PTRzag5rPtaERg+ExN6hNFJoG8ALdKEJX/OizV8/FynmvPDQhA96aXXYXiUgeNVp0t8PgiesBklnuHMvxkSv7+G1GClfXEwTl1ZEhmaCfI3WFROf3n4tC5djyZIpEq,iv:bwcXqZ8m1rmaA2+dxVAvzzwQAO9Di/zCOOF2JRGl9FY=,tag:1duHk0LgtzvpyFZegBQ/Tg==,type:str]
systemd:
    units:
        - name: ENC[AES256_GCM,data:PCEb4nVavXk+1+ezCKIEo9ccRfU=,iv:qbv8AHHm2R5wYAelaz8LiXtMZrs1eA6Wwo8kayEWR8I=,tag:zxiLHVM4FIei4BOWbxSh8A==,type:str]
          enabled: ENC[AES256_GCM,data:FIEWdA==,iv:M8jJBS9jd5x2BCg9YQc82Rs2Happtp9Dql4uDQz6mCo=,tag:8kYIWrYbuKKoZfWoqk2bpQ==,type:bool]
          contents: ENC[AES256_GCM,data:IXtrWkiWFAWCfbVJf+9yDkYtRFfkhqapckZ7NEtLbxmyVB3FbeZMyjb1FHl/gOx2Iypa+8YPAhH0dnKXQ3pJTJV4BwDFUHqZxKUt2SnZ0fHcJAKMKUzBcnVdgNd6CSeKIzea9bdmlOTpBAvef2d/9arhm9LaP5wi2pDvIDybzpmCFErRlbxiBz5iS9llzl/nFTBGEgNq8GgGM1uRTM68DYUtGQqagVktcAZR66O8XLh6HuDhRPvapdS3Wt+Py590OMesFTexad33FNyk0eqSG8Zya8g=,iv:aSZwxA3wxIPLM4s0BfMNacXXJK668L33r4mezHUXfQU=,tag:V0bMjbK5yB4ad0oWAKkA8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-11T21:42:02Z"
    mac: ENC[AES256_GCM,data:EOl0D0oxoOha+LNd3qa4O27RasUBfeZ7TLnO/ndrYWj6LFYnttwOrKjlZZPuHCnLU3aChAMz7McRm/gi7lMNkD/1nrW5kuOlUwmBuM8pKUNj/sX6SvL9kOFbH9CCxZQ44z147UOJZEJE7PmOjlWmi5sVCdOJiHGuEKnSJM7qL6I=,iv:pDSLnWbImWFysVE8RaS1IQ856HVQpttLZIx2Dp0zI/M=,tag:1QlXO+vzMYn1vDU8ZC/RLQ==,type:str]
    pgp:
        - created_at: "2024-11-02T23:09:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA/v+Oq+Qr9g/AQf/VmyCFY6RV/0fnhnmrcNdSwvs3VMTuRmGSTHcKH81e5Q9
            Z27bBPc5Rh6qwYHtJ92yZWkCDK+4Wl0gWVRy3ULLzOQJTjd/Nj0/DE/SjIz7CSdK
            oTlQK+izUmQwDtV1Rnn4haIl2MtLfPB1CACva8nUCLTiNf04Sh0sSLwArukCfXyt
            ucxh/BHZherZGxWCn5aNbngzUEa4PRP0VmG3LA+9uE5OQ5gCGqNYX3jz3yJJa0bB
            bBnFrOdbe3l6gnHaxoOXx23zSZ9gRIuS1MGXRkbg1hTEz64hMImMlwyVMKs78495
            WSVL8+HOToK1+vdf7TweTrTZNEvx8zKIvgNS00ce/NJeAW4OvQLFDNC/cwNURZpU
            beBEhT9e6GZ70RLiFhcPC9YwBep99430hWNVltbJskDP/Rzlh5S3lYGK99URbdo1
            pUVVebjtHSrZNr0rOcb98YvSxImSKyoQR/GEpaYN8A==
            =Hz9R
            -----END PGP MESSAGE-----
          fp: 04AA63BE42B009112842CB5F2968567914AFD2EF
    unencrypted_suffix: _unencrypted
    version: 3.8.1
