#!/bin/sh /etc/rc.common
source /lib/functions.sh

START=02
USE_PROCD=1

# The modem GPIO pinout device might be at a different path
# depending on the kind of GL-iNet device this service runs on.
modem_path() {
  echo '/sys/class/gpio/lte_power/value'
}

set_modem() {
  >&2 echo "attempting to set lte modem to [$1]"
  echo "$1" > "$(modem_path)"
}

start_service() {
  set_modem 1
}

stop_service() {
  set_modem 0
}
